### ISSUE TITLE
Using #include when my code is not in My Documents, includePath/workspace issues

### ISSUE THREAD

**Issue by andymeneely** [rolandostar/tabletopsimulator-lua-vscode#11]
I, like a lot of folks these days, recently switched from Atom to VS Code. When I used the official Atom plugin, I had my setup working where my `Global.-1.ttslua` file has the single line: 

`#include !\timber-wolf\tts\masters-of-the-heist`

And that includes a file called `c:\code\timber-wolf\tts\masters-of-the-heist.ttslua`, which in turn includes other files. So the `!\` part refers to the root of the project (i.e. the folder that atom has opened).

This doesn't seem to work the same way in this extension.  According to the [2017 blog entry](http://blog.onelivesleft.com/2017/08/atom-tabletop-simulator-package.html) I should be able to at least change the expected root in the package settings that `!/`, but I don't see that setting. I do have "Include Other Files" checked so the feature is turned on.

For example `#include c:\code\timber-wolf\tts\masters-of-the-heist` doesn't work. Lots of other variations don't work either - absolute paths, relative `..` paths, forward slashes, all kinds of other things. Every error I get assumes that I'm trying to refer to a subfolder of My Documents (and putting my code in My Documents feels gross to me...)

One thing that happens that is related to this is that I already have a workspace defined, but then when I do "Get Scripts", it blows away my current workspace and creates a new one. Even if I add my folders back, it still always assumes that include is looking in My Documents.

When I look into [your code](https://github.com/rolandostar/tabletopsimulator-lua-vscode/blob/master/src/TTSAdapter.js#L123-L169) it would appear that `includePath` is always just set to `docsFolder` and I can't change that. 

Am I missing something? Is there any way I can have my code in an arbitrary directory and still have `#include` still work?

**Comment by rolandostar** [comment]
Hello Andy!

Thank you for the detailed submission, let me address each point separately.

**1.  On the issue of the `!/` symbol**

I'll investigate on this problem, I can assume it's a bug since most of the include feature isn't thoroughly tested.

**2. Including files from outside `docsFolder`**

Unfortunately this is one the [known issues](https://github.com/rolandostar/tabletopsimulator-lua-vscode/blob/bd1b5d7bf8849b54b2abb3815ad29fb2a77d535c/README.md#known-issues) which I don't really have an ETA on. 

The "Include Other Files" Settings is a simple toggle for the include feature overall, it doesn't particularly deal with all the symbols the blog post you linked mentions. Although I get why the wording could be a bit confusing.

A suggestion for a workaround, it may be possible to use [Window's Symlink](https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/) to create a link between where your code is actually stored and My Documents. 

**3. Workspace redefinition**

I'm not very familiar with the vscode api yet so I just used the first function that managed to create a place to put received files on. Again, not thoroughly tested. Most likely I can use a different function that wouldn't remove the existing workspace. I'll investigate this.

I understand that these issues can be frustrating since they affect existing workflows from Atom, especially for larger projects with edge case requirements. I'm sorry you are having to deal with them, the only answer I can give you is that I'll work on them as time allows since I can only work on this project on my spare time. All PRs welcome.

Thank you again for taking the time of reporting these issues, I'll post any updates here.

**Comment by andymeneely** [comment]
Thanks for the quick response! I didn't see that known issue.

Maybe an easy solution would be to allow `#include` to specify absolute paths? So the order would be 

1. Attempt to resolve the path as-is 
2. Attempt to resolve the path within the directory of the file that is calling the include
3. Attempt to resolve the path according to a setting you have in the extensions, which defaults to what it is now

For the workspace, it looks like their API docs now have an example for adding a folder to the end

```
workspace.updateWorkspaceFolders(workspace.workspaceFolders ? workspace.workspaceFolders.length : 0, null, { uri: ...});
```

Whereas [looks like you've got](https://github.com/rolandostar/tabletopsimulator-lua-vscode/blob/master/src/TTSAdapter.js#L62) that first argument as 0, which would replace things. I think. I'm new to VS code myself.

**Comment by rolandostar** [comment]
Hey, so I've got a prototype that addresses some of these issues, I'm interested if it works out for your use cases. Let me know if you'd like to try it out, I'm on discord most of the time: rolandostar#8942

**Comment by andymeneely** [comment]
Yeah I'd love to try it out! Just sent you a discord friend invite now
