### ISSUE TITLE
command mode functionality in Tabletop Simulator Console++

### ISSUE THREAD

**Issue by E-Leask** [rolandostar/tabletopsimulator-lua-vscode#16]
Hey there,

Sorry if this is the wrong place to ask, I'm looking for a sanity check that command mode is functional with the vscode extension in the Tabletop Simulator Console++.

Running through the console++ example, I get to the point where they're introducing command mode, I can enable it however inputted commands do not function.
![](https://imgur.com/GUdfSfX.gif)
Any thoughts?

Cheers,
Eric

**Comment by rolandostar** [comment]
Hello Eric!

Thanks for the report, I can confirm this is an issue. I'll write the details here to keep track of how I plan to fix this.

According to [this](https://github.com/rolandostar/tabletopsimulator-lua-vscode/blob/master/src/TTSAdapter.ts#L412) there are 2 types of inputs that are done from the TTS Console++ Panel in VSCode. Either Command, or Input. This is controlled by the extension, as such, the extension has no context of Command Mode. When Command mode is switched on, a variable is changed _in-game_ and the extension has no idea, so, whatever input is done in the command textbox is still sent as a normal input to the game per [this line](https://github.com/rolandostar/tabletopsimulator-lua-vscode/blob/master/scripts/vscode/console.lua#L10)

To fix this, the extension needs to keep track when Command Mode is entered. I could look for the `>>` input on the panel. However I'm unsure if Console++ has other means to toggle Command Mode, if so, it may be better to search for `<Command mode: on>` being printed by the game.

I'd be aiming for an update over the weekend since I'm swamped with work atm. 

Thanks again!

**Comment by E-Leask** [comment]
Awesome, thank you!
![](https://tenor.com/view/thumbs-thumbs-up-kid-thumbs-up-meme-brent-ramobjust-gif-19399510.gif)
