### ISSUE TITLE
How does the nested script structure with require() get resolved when uploaded to workshop?

### ISSUE THREAD

**Issue by Sobiru** [rolandostar/tabletopsimulator-lua-vscode#23]
I am currently structuring my scripts in a nested way and using `require("file_name")` to include them in other scripts. This is working well on my local machine, but I am wondering how these external scripts would be resolved when the mod is uploaded to the workshop?

Unfortunately, I am currently unable to upload to the workshop due to some errors in order to test what happens. Therefore, I was hoping I could seek an answer here.

Thank you.

**Comment by rolandostar** [comment]
Requires are resolved at save time. When you send a script to the game (Save & Play) the editor crawls through the references and retrieves content from your file system which is in turn imported into the script *before* being sent to the game.

This means that the savefile that TTS receives contains all code from all requires (with some extra metadata)

The savefile that is uploaded to the workshop is the "extended" version of the code. As if you had gone reference by reference and copy-pasted each file where require'd

You can confirm this by going in-game and opening the script editor. In there you can see the whole thing that VSCode pushes to the game (I'd suggest to avoid modifying it from there since the metadata bits are important)
